name: qrscanner
version: 1.0.0+1
publish_to: none
description: qr code scanner.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  webview_flutter: ^3.0.4
  firebase_auth: ^3.4.1
  google_sign_in: ^5.4.0
  firebase_core: ^1.19.1
  

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/